version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: homecleaning-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: homecleaning
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - homecleaning-network

  redis:
    image: redis:6
    container_name: homecleaning-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - homecleaning-network

volumes:
  postgres_data:
  redis_data:

networks:
  homecleaning-network:
    driver: bridge
